;;; gptel-openrouter-models.el --- Autogenerated list of OpenRouter models for gptel -*- lexical-binding: t -*-

;; Author: Ad <me@skissue.xyz>
;; Maintainer: Ad <me@skissue.xyz>
;; Version: 0.0.1
;; Package-Requires: ((emacs "27.1"))
;; Homepage: https://github.com/skissue
;; Keywords: tools


;; This file is not part of GNU Emacs

;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.


;;; Commentary:

;; Autogenerated list of all OpenRouter models, with appropriate metadata, to
;; pass to `gptel-make-openai'.
;;
;;   (gptel-make-openai "OpenRouter"
;;     :host "openrouter.ai"
;;     :endpoint "/api/v1/chat/completions"
;;     :key "your-openrouter-key"
;;     :models (gptel-openrouter-models))

;;; Code:

(defvar gptel-openrouter-models--file
  (expand-file-name "openrouter-models.json"
                    (file-name-directory (or load-file-name buffer-file-name))))

(defun gptel-openrouter-models--capabilities (model)
  "Derive gptel capabilities list from MODEL hashtable."
  (let* ((arch (gethash "architecture" model))
         (input-modalities (gethash "input_modalities" arch))
         (params (gethash "supported_parameters" model))
         caps)
    ;; Any non-text input modality (image, video, audio, file) counts as
    ;; media in gptel.
    (when (> (length input-modalities) 1)
      (push 'media caps))
    (when (member "tools" params)
      (push 'tool-use caps))
    (when (or (member "response_format" params)
              (member "structured_outputs" params))
      (push 'json caps))
    (when (or (member "reasoning" params)
              (member "include_reasoning" params))
      (push 'reasoning caps))
    caps))

(defun gptel-openrouter-models--mime-types (model)
  "Derive MIME types list from MODEL hashtable."
  (let* ((arch (gethash "architecture" model))
         (input-modalities (gethash "input_modalities" arch))
         types)
    (when (member "image" input-modalities)
      (setq types (append types '("image/jpeg" "image/png" "image/gif" "image/webp"))))
    ;; Anything else under "file"?
    (when (member "file" input-modalities)
      (setq types (append types '("application/pdf"))))
    ;; Is this even supported by gptel?
    (when (member "audio" input-modalities)
      (setq types (append types '("audio/mpeg" "audio/wav"))))
    (when (member "video" input-modalities)
      (setq types (append types '("video/mp4"))))
    types))

(defun gptel-openrouter-models--parse-model (model)
  "Parse a single MODEL hashtable into a gptel model spec."
  (let* ((id (intern (gethash "id" model)))
         (description (car (split-string (or (gethash "description" model) "")
                                         "\n" t)))
         ;; gptel uses thousands of tokens
         (context-window (/ (gethash "context_length" model 0) 1000))
         (pricing (gethash "pricing" model))
         ;; gptel uses $/million tokens
         (input-cost (* (string-to-number (gethash "prompt" pricing "0"))
                        1000000))
         (output-cost (* (string-to-number (gethash "completion" pricing "0"))
                         1000000))
         (capabilities (gptel-openrouter-models--capabilities model))
         (mime-types (gptel-openrouter-models--mime-types model))
         plist)
    (setq plist (list :description description
                      :capabilities capabilities
                      :context-window context-window
                      :input-cost input-cost
                      :output-cost output-cost))
    (when mime-types
      (setq plist (plist-put plist :mime-types mime-types)))
    (cons id plist)))

(defun gptel-openrouter-models ()
  "Return a list suitable for passing to `:models' of `gptel-make-openai'.
Includes all models available on OpenRouter, with metadata and
capabilities specified.  Reads from a bundled `openrouter-models.json'."
  (let ((data (with-temp-buffer
                (insert-file-contents gptel-openrouter-models--file)
                (json-parse-buffer :array-type 'list))))
    (mapcar #'gptel-openrouter-models--parse-model data)))

(provide 'gptel-openrouter-models)

;;; gptel-openrouter-models.el ends here
